export { default as ArrowDownSVG } from './arrow-down';
export { default as FilledHeartSVG } from './filled-heart';
export { default as HeartSVG } from './heart';
export { default as MemeZLogoSVG } from './meme-z-logo';
export { default as OctagonPlusSVG } from './octagon-plus';
export { default as SearchSVG } from './search';
export { default as StarSVG } from './star';
export { default as VerifiedSVG } from './verified';
export { default as WalletSVG } from './wallet';
